version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - MarkEWaite
  labels:
  - skip-changelog
  ignore:
  - dependency-name: io.jenkins*
    versions:
    - ">= 0"
  - dependency-name: org.jenkins-ci.main:jenkins-core
    versions:
    - ">= 0"
  - dependency-name: org.jenkins-ci.plugins*
    versions:
    - ">= 0"
  - dependency-name: org.slf4j*
    versions:
    - ">= 0"
