# Per https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - MarkEWaite
  labels:
  - skip-changelog
  ignore:
  - dependency-name: org.slf4j*
    versions:
    - ">= 0"
- package-ecosystem: docker
  directory: "src/test/resources/org/jvnet/hudson/plugins/platformlabeler/debian/10"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
  target-branch: master
  reviewers:
  - MarkEWaite
  labels:
  - skip-changelog
- package-ecosystem: docker
  directory: "src/test/resources/org/jvnet/hudson/plugins/platformlabeler/centos/8.3.2011/Dockerfile"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
  target-branch: master
  reviewers:
  - MarkEWaite
  labels:
  - skip-changelog
