version: 1

update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "master"
    default_reviewers:
      - "MarkEWaite"
    default_labels:
      - "skip-changelog"
    ignored_updates:
      - match:
          dependency_name: "org.jenkins-ci.main:jenkins-core"
      - match:
          dependency_name: "org.jenkins-ci.plugins*"
      - match:
          dependency_name: "io.jenkins*"
      - match:
          # Required for Jenkins 2.204.2 tests
          dependency_name: "org.slf4j*"
